sudo: required
language: cpp
compiler: gcc
dist: trusty
os: linux

branches:
  only:
  - master

before_install:
  - wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh
  - sudo sh cmake-3.8.2-Linux-x86_64.sh --skip-license --prefix=/usr
  - sudo apt-get install libsfml-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - ./build.sh
script:
  - ./build/build/bin/need-hug-lib-test

notifications:
  email: false
  irc:
    channels:
    - irc.bthstudent.se#nh
    template:
    - "[%{branch}]: %{commit_subject} - %{author} %{build_url}: %{message}"